#!/usr/bin/env node
/**
 * Generates public/sitemap.xml by merging:
 *   - static routes (hardcoded below)
 *   - dynamic blog posts  fetched from the live API
 *   - dynamic service listings fetched from the live API
 *
 * Usage:  node scripts/generate-sitemap.mjs
 * In CI:  add "node scripts/generate-sitemap.mjs" before the vite build step.
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE_URL = 'https://cenner.hr';
const API_BASE = 'https://api.cenner.hr';
const OUTPUT   = join(__dirname, '../public/sitemap.xml');
const TODAY    = new Date().toISOString().split('T')[0];

const STATIC_ROUTES = [
  { path: '/',             priority: '1.0', changefreq: 'weekly'  },
  { path: '/marketplace',  priority: '0.95', changefreq: 'daily'  },
  { path: '/services',     priority: '0.9',  changefreq: 'weekly' },
  // '/match' is deliberately absent: pages/Match.tsx renders <SEO noIndex />, so
  // submitting it here would ask Google to index a page that forbids indexing.
  { path: '/subscription', priority: '0.85', changefreq: 'weekly' },
  { path: '/technology',   priority: '0.8',  changefreq: 'monthly'},
  { path: '/blog',         priority: '0.8',  changefreq: 'daily'  },
  { path: '/about',        priority: '0.75', changefreq: 'monthly'},
  { path: '/contact',      priority: '0.7',  changefreq: 'monthly'},
  { path: '/auth',         priority: '0.5',  changefreq: 'yearly' },
  { path: '/privacy',      priority: '0.3',  changefreq: 'yearly' },
  { path: '/terms',        priority: '0.3',  changefreq: 'yearly' },
  { path: '/cookies',      priority: '0.3',  changefreq: 'yearly' },
];

// Static SEO landing pages generated by scripts/generate-landing-pages.mjs.
// These are the primary keyword-targeted pages and must be in the sitemap.
const LANDING_ROUTES = [
  { path: '/usluge/izrada-web-stranica', priority: '0.9', changefreq: 'weekly' },
  { path: '/usluge/seo-optimizacija',    priority: '0.9', changefreq: 'weekly' },
  { path: '/usluge/digitalni-marketing', priority: '0.9', changefreq: 'weekly' },
  { path: '/usluge/wordpress-izrada',    priority: '0.9', changefreq: 'weekly' },
  { path: '/usluge/dizajn-loga',         priority: '0.9', changefreq: 'weekly' },
  { path: '/usluge/programiranje',       priority: '0.9', changefreq: 'weekly' },
  { path: '/freelanceri/zagreb',         priority: '0.85', changefreq: 'weekly' },
  { path: '/freelanceri/split',          priority: '0.85', changefreq: 'weekly' },
  { path: '/freelanceri/rijeka',         priority: '0.85', changefreq: 'weekly' },
  { path: '/freelanceri/osijek',         priority: '0.85', changefreq: 'weekly' },
];

function urlEntry({ loc, lastmod = TODAY, changefreq = 'monthly', priority = '0.5' }) {
  return `
  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
    <xhtml:link rel="alternate" hreflang="hr"        href="${loc}" />
    <xhtml:link rel="alternate" hreflang="en"        href="${loc}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${loc}" />
  </url>`;
}

async function fetchJson(url) {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json();
  } catch (err) {
    console.warn(`[sitemap] !! Could not fetch ${url}: ${err.message} — ` +
      'continuing with static routes only. If this is unexpected, the URL is wrong ' +
      'or the API is unreachable; do not treat the resulting sitemap as complete.');
    return [];
  }
}

async function main() {
  const entries = [];

  // Static routes
  for (const r of STATIC_ROUTES) {
    entries.push(urlEntry({ loc: `${BASE_URL}${r.path}`, changefreq: r.changefreq, priority: r.priority }));
  }

  // Static SEO landing pages
  for (const r of LANDING_ROUTES) {
    entries.push(urlEntry({ loc: `${BASE_URL}${r.path}`, changefreq: r.changefreq, priority: r.priority }));
  }

  // Dynamic: blog posts.
  // NOTE: the collection route is /api/v1/public/blog — a bare /blog is a 404 on
  // this API and fetchJson used to swallow it, so this loop silently did nothing.
  const posts = await fetchJson(`${API_BASE}/api/v1/public/blog`);
  for (const post of posts) {
    if (!post.slug || post.published === false) continue;
    entries.push(urlEntry({
      loc: `${BASE_URL}/blog/${encodeURIComponent(post.slug)}`,
      lastmod: (post.updatedAt || post.publishedAt || TODAY).split('T')[0],
      changefreq: 'monthly',
      priority: '0.7',
    }));
  }

  // Service and freelancer pages are deliberately NOT built here. This API exposes
  // no public collection endpoint for them (only /api/v1/public/listings/:id and
  // /api/v1/public/freelancers/:id), and the backend already serves the full set from
  // its own DB at https://api.cenner.hr/sitemap-dynamic.xml, which robots.txt lists as
  // a second sitemap. Enumerating them a second time from here would only drift.

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">${entries.join('')}
</urlset>
`;

  writeFileSync(OUTPUT, xml, 'utf8');
  console.log(`[sitemap] Written ${entries.length} URLs → ${OUTPUT}`);
}

main().catch(err => { console.error(err); process.exit(1); });
